version: '3'
services:
    brain:
        build:
            context: .
            dockerfile: ./src/brain/Dockerfile
        command: npm run brain:prod
        ports:
            - '3000:8080'
        environment:
            DEBUG: '*'
