version: '2'
services:
    brain:
        build:
            context: .
            dockerfile: ./src/brain/Dockerfile
        command: 'npm run brain:prod'
        expose:
            - '8080'
        environment:
            DEBUG: '*'
        # map the ./data folder to our data volume defined below
        volumes:
            - brain-data:/usr/brain/data
    slackbot:
        build:
            context: .
            dockerfile: ./src/slackbot/Dockerfile
        command: 'npm run bot:prod -- --brainURL=http://brain:8080'
        environment:
            DEBUG: '*'
    web:
        build:
            # No root context here
            context: .
            dockerfile: ./src/web/Dockerfile
        command: 'npm run serve'
        ports:
            - 5000:5000
        environment:
            DEBUG: '*'

# Create a named volume for our brain data
volumes:
    brain-data:
